# -*- coding: utf-8 -*-
"""activite

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zs78y-E3W9D8wrDmd3Lq_v0VdGrud19n
"""

import pandas as pd
data=pd.read_csv('/content/tips.csv')
print(data)

import matplotlib.pyplot as plt
import pandas as pd
data=pd.read_csv('/content/tips.csv')
plt.hist(data['day'],color='blue',alpha=0.7)
plt.xlabel('day')
plt.ylabel('frequency')
plt.title('histplot')
plt.show()

plt.hist(data['day'],bins=10)
plt.hist(data['sex'],bins=10)
plt.show()

plt.scatter(x='day',y='tip',data=data)
plt.xlabel('day')
plt.ylabel('tip')
plt.show()

import matplotlib.pyplot as plt
plt.boxplot(data['tip'])
plt.show()

import matplotlib.pyplot as plt
x=data['tip']
y=data['day']
plt.bar(x,y,width=5)
plt.show()

import pandas as pd
data=pd.read_csv('/content/mtcars.csv')
print(data)

import seaborn as sns
plt.figure(figsize=(15,5))
plt.subplot(131)
sns.histplot(data['mpg'],kde=True)
plt.subplot(132)
sns.boxplot(x='cylinders', data=data)
plt.title("box plot of hp")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(15, 5))
plt.subplot(131)
sns.histplot(data['mpg'], kde=True)
plt.title('Histogram of MPG')
plt.subplot(132)
sns.boxplot(x='cylinders', data=data)
plt.title('Boxplot of Cylinders')
plt.show()

import numpy as np
import pandas as pd
data=pd.read_csv('/content/tips.csv')
data.head()

missing_values=data.isnull().sum()
print("missing values:\n",missing_values)

import matplotlib.pyplot as plt
import pandas as pd
data={
    'tips':[10,20,30,40,50,60,70,80,90,100],
}
data=pd.dataframe(data)
z_score=(data['tips']-data['tips'].mean())/data['tips'].std()
threshold=3
outliers=data[(z_score>threshold)]